# You can use either:
#   mode: train
# or set train/evaluate/predict booleans directly (both supported by the code change below).
mode: train

domain: "SO_JET"

data_dir: "/gws/nopw/j04/ai4pex/twilder/NEMO_data/DINO/EXP16/features/{domain}/coarsened_data/"
model_dir: "/home/users/twilder/Python/AI4PEX/machine_learning/training/"

data_filenames: >
  MINT_1d_0061-0072_sa_c_{domain}.nc
  MINT_1d_0061-0072_vor_cg_{domain}_mod.nc
  MINT_1d_0061-0072_eke_c_{domain}_shifted.nc
  MINT_1d_0061-0072_mke_c_{domain}.nc
  mesh_mask_exp4_{domain}_xnemo.nc

features: "mke vor sa"
target: "eke"

filters: "128 64 32 16 8 1"
kernels: "(5,5) (5,5) (3,3) (3,3) (3,3) (3,3)"
padding: "(2,2) (2,2) (1,1) (1,1) (1,1) (1,1)"

batch_size: 15
epochs: 100
k_folds: 1
learning_rate: 0.001
dropout_rate: 0.2
use_learning_rate_scheduler: false
pickup: false

local_norm: true
global_norm: false

verbose: true
verbose_output_filename: "./logs/verbose_output.log"
tensboard_log_dir: "./logs/fit/"